config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
  end


  get 'qr_codes/new'
  get 'qr_codes/create'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'


  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about' 
  get '/contact', to: 'static_pages#contact'
  get '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :qr_codes, only: [:new, :create]
  resources :registered_pets
  resources :products, only: [:new]
  resources :products_in_carts, only: [:new, :create]
  root to: "qr_codes#new"

  delete 'avatar/:id', to: 'registered_pets#destroy_avatar', as: 'avatar'
 



end

app/models/registered_pet.rb
class RegisteredPet < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  has_one :collar
  belongs_to :user
  validates_processing_of :avatar
  validate :avatar_size_validation

  private
  def avatar_size_validation
    errors[:avatar] << "debe ser menor a 900KB" if avatar.size > 0.9.megabytes
  end
 
end

app/controllers/registered_pets_controller.rb
class RegisteredPetsController < ApplicationController
  def new
    @pet = RegisteredPet.new
  end

  def create
    parameters = params[:registered_pet]
    user = current_user
    @pet = RegisteredPet.new(registered_pet_params)
    if @pet.save
      user.registered_pets << @pet
      flash[:success] = "Mascota registrada exitosamente"
      redirect_to @pet
    else
      render 'form'
    end
  end

  def show
    @pet = RegisteredPet.find(params[:id])
    @user = @pet.user
  end


  def edit
    @pet = RegisteredPet.find(params[:id])
      unless current_user == @pet.user
        flash[:danger] = "No puedes editar a esta mascota"
        redirect_to @pet
      end
  end

  def update
    @pet = RegisteredPet.find(params[:id])
    if @pet.update_attributes(registered_pet_params)
      flash[:success] = "Cambios guardados exitosamente!"
      redirect_to @pet
    else
      render 'edit'
    end
  end

  def destroy
    RegisteredPet.find(params[:id]).destroy
    flash[:success] = "Mascota eliminada"
    redirect_to user_path(current_user)
  end

  def destroy_avatar
    @pet = RegisteredPet.find(params[:id])
    @pet.remove_avatar!
    @pet.save
    flash[:success] = "Avatar deleted"
    redirect_to registered_pet_path
  end

  private


    def registered_pet_params
      params.require(:registered_pet).permit(:pet_name, :pet_age, :pet_disease, :pet_vaccines, :pet_info, :owner_name, :owner_phone, :avatar)
    end


    def must_be_owner
    unless current_user && @pet.user
      redirect_to show_path(@pet), notice: "No tienes los permisos para hacer esto"
    end
    end
end

app/helpers/registered_pets_helper.rb
module RegisteredPetsHelper
end

app/views/registered_pets/_form.html.erb
<%= form_for(@pet) do |f| %>
  
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>
 
      <ul>
      <% @pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :nombre %>
  <%= f.text_field :pet_name, class: 'form-control' %>

  <%= f.label :edad %>
  <%= f.text_field :pet_age, class: 'form-control' %>

  <%= f.label :enfermedades %>
  <%= f.text_field :pet_disease, class: 'form-control' %>

  <%= f.label :vacunas %>
  <%= f.text_field :pet_vaccines, class: 'form-control' %>

  <%= f.label :comentarios %>
  <%= f.text_area :pet_info, class: 'form-control' %>


  <%= f.label :contacto %>
  <%= f.text_field :owner_name, class: 'form-control' %>

  <%= f.label :telefono %>
  <%= f.phone_field :owner_phone, class: 'form-control' %>
   
    <%= f.label :foto %><br>
    <%= f.file_field :avatar %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/registered_pets/_picture.html.erb
<div id="picture-form"><%= form_for(@pet) do |f| %>
  
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>
 
      <ul>
      <% @pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.label :foto %><br>
    <%= f.file_field :avatar %>

  <%= f.submit "Subir foto", class: "btn btn-primary" %>
<% end %>
</div>

app/views/registered_pets/create.html.erb
<div id="pet-profile">
  <ul>
      <li>Nombre de la mascota: <%= @pet.pet_name %></li>
      <li>Edad: <%= @pet.pet_age %></li>
      <li>Enfermedades: <%= @pet.pet_disease %></li>
      <li>Vacunas: <%= @pet.pet_vaccines %></li>
      <li>Comentarios: <%= @pet.pet_info %></li>
      <li>Contacto: <%= @pet.owner_name %></li>
      <li>Teléfono: <%= @pet.owner_phone %></li>
  </ul>
</div>  

app/views/registered_pets/edit.html.erb
<% provide(:title, "Edit pet profile" ) %>
<% provide(:button_text, 'Guardar') %>
<h1>Edita el perfil de tu mascota</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

<script type="text/javascript">

</script>

app/views/registered_pets/new.html.erb
<% provide(:title, 'Registra tu mascota') %>
<% provide(:button_text, 'Guardar') %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/registered_pets/show.html.erb
<% provide(:title, @pet.pet_name) %>
<div class="container">
  <div class="well well-sm">
    <div class="col-sm-6 col-md-4">
        <% if @pet.avatar.file.nil? && current_user == @user %> 
           <%= render 'picture' %>
        <% elsif @pet.avatar && current_user == @user %>
           <%= image_tag @pet.avatar.thumb.url %>
           <br>
           <br>
           <div class="btn-group">
               <%= link_to "Eliminar foto", avatar_path(@pet), method: :delete, data: { confirm: "¿Estás seguro?" }, class: "btn btn-primary" %>
           </div>     
        <% elsif @pet.avatar.file.nil? %> 
           <img src="http://placehold.it/380x500" alt="" class="img-rounded img-responsive" />  
        <% else %>
          <%= image_tag @pet.avatar.thumb.url %>
        <% end %>
    </div>
    <div class="col-sm-6 col-md-8" style="padding-left: 5%;">
        <h4> <%= @pet.pet_name %></h4>
        <small><cite title="Cuidad de México">Ciudad de México, Mx<i class="glyphicon glyphicon-map-marker">
        </i></cite></small>
        <p>
            <i class="glyphicon glyphicon-time"></i><b>Edad:</b> <%= @pet.pet_age %>
            <br />
            <i class="glyphicon glyphicon-plus-sign"></i><b>Enfermedades:</b> <%= @pet.pet_disease %>
            <br />
            <i class="glyphicon glyphicon-briefcase"></i><b>Vacunas:</b> <%= @pet.pet_vaccines %>
            <br />
            <i class="glyphicon glyphicon-comment"></i><b>Comentarios:</b> <%= @pet.pet_info %>
            <br />
            <i class="glyphicon glyphicon-user"></i><b>Contacto:</b> <%= @pet.owner_name %>
            <br />
            <i class="glyphicon glyphicon-earphone"></i><b>Teléfono:
          </b> <%= @pet.owner_phone %></p>


        <% if current_user == @user %>
        <div class="btn-group">
            <button type="button" class="btn btn-primary">
                Settings</button>
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                <span class="caret"></span><span class="sr-only">Settings</span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Edit", edit_registered_pet_path(@pet) %></li>
                <li> <%= link_to "Borrar", registered_pet_path(@pet), method: :delete, data: { confirm: "You sure?" } %></li>
            </ul>
        </div>
        <% end %>
    </div>
  </div>
</div>