config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
  end


  get 'qr_codes/new'
  get 'qr_codes/create'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'


  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about' 
  get '/contact', to: 'static_pages#contact'
  get '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :qr_codes, only: [:new, :create]
  resources :registered_pets
  resources :products, only: [:new]
  resources :products_in_carts, only: [:new, :create]
  root to: "qr_codes#new"

  delete 'avatar/:id', to: 'registered_pets#destroy_avatar', as: 'avatar'
 



end

app/models/user.rb
class User < ApplicationRecord
  has_many :addresses, dependent: :destroy, inverse_of: :user
  accepts_nested_attributes_for :addresses, allow_destroy: true#, reject_if: ->(attrs) { attrs['full_name'].blank? || attrs['country'].blank? || attrs['zip'].blank? || attrs['state'].blank? || attrs['city'].blank?  || attrs['street'].blank? || attrs['number'].blank? }
  has_many :registered_pets
  has_many :user_products
  has_many :products, :through => :user_products
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

 
    # Returns the hash digest of the given string.
    def self.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def self.new_token
      SecureRandom.urlsafe_base64
    end

    # Remembers a user in the database for use in persistent sessions.
    def remember
      self.remember_token = User.new_token
      update_attribute(:remember_digest, User.digest(remember_token))
    end

    # Returns true if the given token matches the digest.
    def authenticated?(attribute, token)
      digest = send("#{attribute}_digest")
      return false if digest.nil?
      BCrypt::Password.new(digest).is_password?(token)
    end
    
    # Forgets a user.
    def forget
      update_attribute(:remember_digest, nil)
    end

      # Activates an account.
    def activate
      update_attribute(:activated,    true)
      update_attribute(:activated_at, Time.zone.now)
    end

    # Sends activation email.
    def send_activation_email
      UserMailer.account_activation(self).deliver_now
    end
    
    # Sets the password reset attributes.
    def create_reset_digest
      self.reset_token = User.new_token
      update_attribute(:reset_digest,  User.digest(reset_token))
      update_attribute(:reset_sent_at, Time.zone.now)
    end

    # Sends password reset email.
    def send_password_reset_email
      UserMailer.password_reset(self).deliver_now
    end

    # Returns true if a password reset has expired.
    def password_reset_expired?
      reset_sent_at < 2.hours.ago
    end

    def cart?
      Cart.find_or_create_by(user_id: id)
    end

    private



    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def index
   @users = User.paginate(page: params[:page])
  end

  def create
    @user = User.new(user_params)
    puts "USER PARAMS"
    p user_params
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to user_url
  end


  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, addresses_attributes: [:id, :full_name, :country, :zip, :state, :city, :province, :street, :number, :int, :tel])
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :nombre %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :correo_electronico %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :contraseña %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :confirmacion_contraseña %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
  <strong> Dirección de entrega (opcional)</strong>
    <br>
    <br>
      <%= f.label :pais %>
      <%= f.text_field :country, class: 'form-control' %>

      <%= f.label :codigo_postal %>
      <%= f.text_field :zip, class: 'form-control' %>

      <%= f.label :Estado %>
      <%= f.text_field :state, class: 'form-control' %>
     
      <%= f.label :ciudad %>
      <%= f.text_field :city, class: 'form-control' %>
     
      <%= f.label :provincia %>
      <%= f.text_field :province, class: 'form-control' %>
     
      <%= f.label :calle %>
      <%= f.text_field :street, class: 'form-control' %>
     
      <%= f.label :numero%>
      <%= f.text_field :number, class: 'form-control' %>
     
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>mosca
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <%= link_to "Registra tu mascota", controller: "registered_pets", action: "new" %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Editar perfil') %>
<% provide(:button_text, 'Guardar') %>
<h1>Edita tu perfil</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">Change</a>
    </div>
  </div>
</div>

<script type="text/javascript">

</script>

app/views/users/new.html.erb
<% provide(:title, 'Regístrate') %>
<% provide(:button_text, 'Crea mi cuenta') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/register.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :pet_name %>
  <%= f.text_field :pet_name, class: 'form-control' %>

  <%= f.label :pet_age %>
  <%= f.text_field :pet_age, class: 'form-control' %>

  <%= f.label :pet_disease %>
  <%= f.text_field :pet_disease, class: 'form-control' %>

  <%= f.label :pet_vaccines %>
  <%= f.text_field :pet_vaccines, class: 'form-control' %>

  <%= f.label :pet_info %>
  <%= f.text_area :pet_info, class: 'form-control' %>


  <%= f.label :owner_name %>
  <%= f.text_field :owner_name, class: 'form-control' %>

  <%= f.label :owner_phone %>
  <%= f.phone_field :owner_phone, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="container">
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
          <h1><%= @user.name %></h1>
          <br>
            <% if @user.registered_pets.empty? && @user.code == true %>
              <h3> Aún no tienes mascotas registradas </h3>
            <% else %>
              <div id="user-pets">
                <% @user.registered_pets.each do |pet| %>
                  <%= link_to "#{pet.pet_name}",registered_pet_path(pet), class: "btn btn-primary" %>
                  <br>
                <% end %>  
              </div>
            <% end %> 
                <% if @user.code == true %>
                  <%= link_to "Registra tu mascota", new_registered_pet_path %>
                <% end %>  


      </section>
    </aside>
  </div>

  <div class="container">
      <div class="row">
          <div class="col-md-3">
              <ul class="nav nav-pills nav-stacked">
                  <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
                  <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "Domicilio de entrega", about_path %></li>
                  <li class="<%= 'active' if current_page?(contact_path) %>"><%= link_to "Contact", contact_path %></li>
              </ul>
          </div>
          <div class="col-md-9 well">
              Vertical admin menu
          </div>
      </div>
  </div>
</div>