config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
  end


  get 'qr_codes/new'
  get 'qr_codes/create'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'


  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about' 
  get '/contact', to: 'static_pages#contact'
  get '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :qr_codes, only: [:new, :create]
  resources :registered_pets
  resources :products, only: [:new]
  resources :products_in_carts, only: [:new, :create]
  root to: "qr_codes#new"

  delete 'avatar/:id', to: 'registered_pets#destroy_avatar', as: 'avatar'
 



end

app/controllers/qr_codes_controller.rb
class QrCodesController < ApplicationController
  def new
  end

  def create
    random = Array.new(7){[*"A".."Z", *"a".."z", *"0".."9"].sample}.join
    @qr = RQRCode::QRCode.new( qr_code_params[:text], size: 5, :level => :h)
    png = @qr.to_img                                             # returns an instance of ChunkyPNG
    png.resize(90, 90).save("#{random}.png")

  end

private
  def qr_code_params
    params.require(:qr_code).permit(:text)
  end
end

app/helpers/qr_codes_helper.rb
module QrCodesHelper
end

app/views/qr_codes/create.html.erb
<table class="qr-code">
<% @qr.modules.each_index do |x| %>
  <tr>
  <% @qr.modules.each_index do |y| %>
   <% if @qr.dark?(x,y) %>
    <td class="black"/>
   <% else %>
    <td class="white"/>
   <% end %>
  <% end %>
  </tr>
<% end %>
</table>
<br />
<br />
<%= link_to "New QR Code", new_qr_code_path %>

app/views/qr_codes/new.html.erb
<%= form_for :qr_code, url: qr_codes_path do |f| %>
  <%= f.label :text %>
  <%= f.text_field :text %>
  <%= f.submit %>
<% end %>