config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
  end


  get 'qr_codes/new'
  get 'qr_codes/create'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'


  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about' 
  get '/contact', to: 'static_pages#contact'
  get '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :qr_codes, only: [:new, :create]
  resources :registered_pets
  resources :products, only: [:new]
  resources :products_in_carts, only: [:new, :create]
  root to: "qr_codes#new"

  delete 'avatar/:id', to: 'registered_pets#destroy_avatar', as: 'avatar'
 



end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="container">
    <nav class="navbar navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar" style="color: white;"></span>
          <span class="icon-bar" style="color: white;"></span>
          <span class="icon-bar" style="color: white;"></span>
          </button>

           <a class="navbar-brand" href="http://petito.com"><img src="https://img.clipartfest.com/5be9643fc5abd32732ddc30f42f034c5_green-dog-paw-clip-art-dog-paw-patrol-logo-clipart-free_1024-938.png" alt="Petito">
           </a>
        </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Productos<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Cat's collars</a></li>
              <li><a href="#">Dog's collars</a></li>
              <li><a href="#">Cat products</a></li>
            </ul>
            <li><%= link_to "Sign up", signup_path %></li>
              <% if logged_in? %>
              <li><%= link_to "Account", current_user %>
              </li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li><%= link_to "Log out", logout_path, method: "delete" %></li>
              <% else %>
                <li><%= link_to "Log in", login_path %></li>
              <% end %>
           </ul>
          </div>
      </div>

    </nav>
  </div>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head><link rel="shortcut icon" href="http://cdn.mysitemyway.com/etc-mysitemyway/icons/legacy-previews/icons/blue-jelly-icons-animals/011447-blue-jelly-icon-animals-animal-cat-print.png"/><title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1" />
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
         <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>